package chatline;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class SignupForm extends javax.swing.JFrame {

    Connection con;
    public SignupForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        Border labelBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        closeIcon.setBorder(labelBorder);
        miniIcon.setBorder(labelBorder);
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/Chat", "chat", "000");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_fn = new javax.swing.JTextField();
        jTextField_ln = new javax.swing.JTextField();
        jTextField_dpt = new javax.swing.JTextField();
        jTextField_sid = new javax.swing.JTextField();
        jTextField_cno = new javax.swing.JTextField();
        userName = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        cbut = new javax.swing.JButton();
        canbut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        closeIcon = new javax.swing.JLabel();
        miniIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(136, 204, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("First Name");

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Last Name");

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Student ID");

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Department");

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Contact No");

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("User Name");

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Password");

        jTextField_fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fnActionPerformed(evt);
            }
        });

        jTextField_sid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_sidKeyTyped(evt);
            }
        });

        jTextField_cno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_cnoKeyTyped(evt);
            }
        });

        userName.setForeground(new java.awt.Color(153, 153, 153));
        userName.setText("AUST Mail ID");
        userName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameFocusLost(evt);
            }
        });

        cbut.setBackground(new java.awt.Color(0, 153, 51));
        cbut.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        cbut.setText("Create Account");
        cbut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbutFocusGained(evt);
            }
        });
        cbut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbutMouseExited(evt);
            }
        });
        cbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbutActionPerformed(evt);
            }
        });

        canbut.setBackground(new java.awt.Color(255, 51, 51));
        canbut.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        canbut.setText("Cancel");
        canbut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                canbutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                canbutMouseExited(evt);
            }
        });
        canbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canbutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_fn)
                            .addComponent(jTextField_ln, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_dpt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_sid, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_cno)
                            .addComponent(userName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(canbut, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbut, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_fn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_ln, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_sid, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_dpt, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_cno, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel8))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canbut, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbut, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(435, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jLabel1.setText("Sign Up");

        closeIcon.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        closeIcon.setText("X");
        closeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeIconMouseExited(evt);
            }
        });

        miniIcon.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        miniIcon.setText("-");
        miniIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(miniIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeIcon)
                .addGap(8, 8, 8))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(miniIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeIconMouseClicked

    private void miniIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniIconMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_miniIconMouseClicked

    private void jTextField_fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fnActionPerformed

    private void canbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canbutActionPerformed
        LoginForm lif = new LoginForm();
        lif.setVisible(true);
        lif.pack();
        lif.setLocationRelativeTo(null);
        lif.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_canbutActionPerformed

    private void miniIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniIconMouseEntered
        Border labelBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.blue);
        miniIcon.setBorder(labelBorder);
        miniIcon.setForeground(Color.blue);
    }//GEN-LAST:event_miniIconMouseEntered

    private void miniIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniIconMouseExited
        Border labelBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        miniIcon.setBorder(labelBorder);
        miniIcon.setForeground(Color.black);
    }//GEN-LAST:event_miniIconMouseExited

    private void closeIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseEntered
        Border labelBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.blue);
        closeIcon.setBorder(labelBorder);
        closeIcon.setForeground(Color.blue);
    }//GEN-LAST:event_closeIconMouseEntered

    private void closeIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseExited
        Border labelBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        closeIcon.setBorder(labelBorder);
        closeIcon.setForeground(Color.black);
    }//GEN-LAST:event_closeIconMouseExited

    private void cbutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbutFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cbutFocusGained

    private void cbutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbutMouseEntered
        cbut.setBackground(new Color(0,102,51));
    }//GEN-LAST:event_cbutMouseEntered

    private void cbutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbutMouseExited
        cbut.setBackground(new Color(0,153,51));
    }//GEN-LAST:event_cbutMouseExited

    private void canbutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canbutMouseEntered
        canbut.setBackground(new Color(255,0,51));
    }//GEN-LAST:event_canbutMouseEntered

    private void canbutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canbutMouseExited
        canbut.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_canbutMouseExited

    private void userNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFocusGained
        if(userName.getText().trim().toLowerCase().equalsIgnoreCase("AUST Mail ID")){
            userName.setText("");
            userName.setForeground(Color.black);
        }
    }//GEN-LAST:event_userNameFocusGained

    private void userNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFocusLost
        if(userName.getText().trim().equals("") || userName.getText().trim().toLowerCase().equals("AUST Mail ID")){
            userName.setText("AUST Mail ID");
            userName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_userNameFocusLost

    private void jTextField_cnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_cnoKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_cnoKeyTyped

    private void jTextField_sidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_sidKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_sidKeyTyped

    private void cbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbutActionPerformed
        String fname = jTextField_fn.getText();
        String lname = jTextField_ln.getText();
        String stID = jTextField_sid.getText();
        String dept = jTextField_dpt.getText();
        String contNo = jTextField_cno.getText();
        String uname = userName.getText();
        String pass = String.valueOf(jPasswordField1.getPassword());
        if(verifyFields()){
            if(!checkUsername(uname)){
                PreparedStatement ps;
                ResultSet rs;
                String regUserQuery = "INSERT INTO INFO(FIRST_NAME, LAST_NAME, STD_ID, DEPT, CONT_NO, U_NAME, PASSWORD) VALUES (?,?,?,?,?,?,?)";
                if(!validUsername(uname)){
                    JOptionPane.showMessageDialog(null, "Invalid Email!");
                }else{
                    try {
                        ps = con.prepareStatement(regUserQuery);
                        ps.setString(1, fname);
                        ps.setString(2, lname);
                        ps.setString(3, stID);
                        ps.setString(4, dept);
                        ps.setString(5, contNo);
                        ps.setString(6, uname);
                        ps.setString(7, pass);
                        if(ps.executeUpdate() != 0){
                            JOptionPane.showMessageDialog(null, "Your account has been created");
                            jTextField_fn.setText("");
                            jTextField_ln.setText("");
                            jTextField_sid.setText("");
                            jTextField_dpt.setText("");
                            jTextField_cno.setText("");
                            userName.setText("");
                            jPasswordField1.setText("");
                            
                        }else{
                            JOptionPane.showMessageDialog(null, "Error! Check your informations");
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(SignupForm.class.getName()).log(Level.SEVERE, null, ex);
                    }  
                }
         

            }
        }
    }//GEN-LAST:event_cbutActionPerformed
    
    private int xMouse,yMouse;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public boolean verifyFields(){
        String fname = jTextField_fn.getText();
        String lname = jTextField_ln.getText();
        String stID = jTextField_sid.getText();
        String dept = jTextField_dpt.getText();
        String contNo = jTextField_cno.getText();
        String uname = userName.getText();
        String pass = String.valueOf(jPasswordField1.getPassword());
        if(fname.trim().equals("") || lname.trim().equals("") || stID.trim().equals("") || dept.trim().equals("") || contNo.trim().equals("") || uname.trim().equals("") || pass.trim().equals("")){
            JOptionPane.showMessageDialog(null, "One or more fields are empty", "Empty Fields", 2);
            return false;
        }
        else
            return true;
    }
    public boolean checkUsername(String username){
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;
        String query = "SELECT * FROM INFO WHERE U_NAME = ?";
        try {
            st = con.prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
            if(rs.next()){
                username_exist = true;
                JOptionPane.showMessageDialog(null, "User Name Already Taken", "Username Failed", 2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(SignupForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return username_exist;
    }
    public boolean validUsername(String input){
        String mailreg = "^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$";
        Pattern mailpat = Pattern.compile(mailreg, Pattern.CASE_INSENSITIVE);
        Matcher mat = mailpat.matcher(input);
        return mat.find();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canbut;
    private javax.swing.JButton cbut;
    private javax.swing.JLabel closeIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField_cno;
    private javax.swing.JTextField jTextField_dpt;
    private javax.swing.JTextField jTextField_fn;
    private javax.swing.JTextField jTextField_ln;
    private javax.swing.JTextField jTextField_sid;
    private javax.swing.JLabel miniIcon;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
